version: 1
services:
  - type: web
    name: sqli-scanner
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: sqli-db
          property: connectionString
    healthCheckPath: /

  - type: pserv
    name: sqli-db
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: sqli_scanner
      - key: POSTGRES_USER
        value: scanner
      - key: POSTGRES_PASSWORD
        generateValue: true
